print("Hello Humans!")
print("What's your name?")
myName = input()
print("It's good to meet you, " + myName)
print("The length of your name is :")
print(len(myName))
print("How old are you? ")
old = input()
print("You will be " + str(int(old)+1) + " next year")
